### PR TITLE
Removed the attributesToHighlight search parameter #336 

### LINKED ISSUE #336: Remove the `attributesToHighlight` search parameter
We currently specify the `attributesToHighlight` search parameter in the code, but since we don't highlight any attribute on search in the demo, we can remove it.

To learn more about the `attributesToHighlight` search parameter:
[https://docs.meilisearch.com/reference/api/search.html#attributes-to-highlight](https://docs.meilisearch.com/reference/api/search.html#attributes-to-highlight
)

### PR DESCRIPTION
**Pull request by island-coder**
# Pull Request

Fixes #336

### CODE REVIEW

**Comment by mdubus** [comment]
Hello @island-coder  👋 

I'm really sorry for the delay, I was off last week and just came back today! 
I can see that there is a small linter issue in your PR, can you please fix it? The `yarn lint:fix` might help you 😉 

Thanks a lot! 🙏

**Comment by island-coder** [comment]
> Hello @island-coder 👋
> 
> I'm really sorry for the delay, I was off last week and just came back today! I can see that there is a small linter issue in your PR, can you please fix it? The `yarn lint:fix` might help you 😉
> 
> Thanks a lot! 🙏

No problem at all! Please review when you are free 👍🏼

**Comment by mdubus** [comment]
Hi @island-coder 👋 

Thanks a lot for your understanding 😃
You still have a small linter problem. I think you are now missing one whitespace 🤭 FYI, we are using ESLint and Prettier on this project. This should be all good after this. 

Thanks a lot!

**Comment by mdubus** [comment]
This is perfect now, thanks a lot for your update 🚀 🎉

bors merge

**Comment by island-coder** [comment]
> This is perfect now, thanks a lot for your update 🚀 🎉
> 
> bors merge

Glad to help 😃 👍🏼

**Pull request merged**
