### PR TITLE
replace meilisearch env variables

### LINKED ISSUE #373: Rename environment variables to include `Meilisearch` in it
Currently, we have two environment variables that are being used:

- `HOST`
- `API_KEY`

We would like to rename them and include `Meilisearch` in it to avoid confusion. 

They should be renamed as follow:

- `MEILISEARCH_HOST`
- ~~MEILISEARCH_MASTER_KEY~~ -> `MEILISEARCH_API_KEY`

Make sure to rename them everywhere (code, Readme, tests, environment files, ...)

⚠ Once it's done, a maintainer must update the credentials on Vercel

### PR DESCRIPTION
**Pull request by SurojN**
# Pull Request

## Related issue
Fixes #373 

## What does this PR do?
- ...

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Comment by SurojN** [comment]
@mdubus please review the PR

**Comment by mdubus** [comment]
Hello @SurojN  👋

Thanks a lot for your PR. I will review it when I have time

**Comment by Smartmind12** [comment]
@mdubus This PR is a replica of the #376 that was created by me and reviewed by you !

**Comment by mdubus** [comment]
Hello @SurojN 👋

Thanks a lot for your PR. I decided to merge the [following PR](https://github.com/meilisearch/demo-movies/pull/376) which solves the same issue as your PR, because it was created first.

Therefore, I'm closing your PR as the issue is now solved, I hope you'll understand it.

Have a nice day! ✨ 🦕

**Pull request closed without merging**
